listen=YES
listen_ipv6=NO
listen_address=192.168.1.150
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=077
chroot_local_user=YES
user_sub_token=$USER
local_root=/srv/ftp/$USER
userlist_enable=YES
userlist_deny=NO
userlist_file=/etc/vsftpd.userlist
pam_service_name=vsftpd
secure_chroot_dir=/var/run/vsftpd/empty
xferlog_enable=YES
pasv_enable=YES
pasv_min_port=40000
pasv_max_port=40010
pasv_address=192.168.1.150
ssl_enable=YES
allow_anon_ssl=NO
force_local_logins_ssl=YES
force_local_data_ssl=YES
ssl_sslv2=NO
ssl_sslv3=NO
ssl_tlsv1=YES
require_ssl_reuse=NO
rsa_cert_file=/etc/ssl/certs/week7-ftps.crt
rsa_private_key_file=/etc/ssl/private/week7-ftps.key
